---
- name: Clone the dvmprov repository
  ansible.builtin.git:
    repo: 'https://github.com/DVMProject/dvmprov'
    dest: '/opt/{{ dvm_folder }}/dvmprov'
    clone: yes
    update: yes

- name: Create a Python virtual environment
  ansible.builtin.command: "python3 -m venv /opt/{{ dvm_folder }}/dvmprov/"
  args:
    creates: "/opt/{{ dvm_folder }}/dvmprov/bin/activate"

- name: Install Python packages from requirements.txt
  ansible.builtin.pip:
    requirements: "/opt/{{ dvm_folder }}/dvmprov/requirements.txt"
    virtualenv: "/opt/{{ dvm_folder }}/dvmprov/"

- name: Generate dvmprov configuration from template
  ansible.builtin.template:
    src: templates/configs/rest.py.j2
    dest: "/opt/{{ dvm_folder }}/dvmprov/rest.py"

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/services/dvmprov.service.j2"
    dest: "/etc/systemd/system/dvmprov.service"

- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start the dvmprov service
  ansible.builtin.systemd:
    name: dvmprov.service
    enabled: yes
    state: started
